### ISSUE TITLE
Dataset: patch --> crowd label

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#109]
Document how labels are generated.

**Comment by MatthewJA** [comment]
132a67f adds a module that pulls the dataset from the raw features and labels. It's pretty simple.

I'll document the labels in my thesis and another document to go with the dataset.

**Comment by MatthewJA** [comment]
Regarding making the labels more informative (by changing the binary label to some kind of agreement percentage): This probably needs to be based on radio agreement, since from my earlier notebooks I found that when people agree on radio they tend to agree on infrared location. One problem is that I'm currently labelling the nearest infrared object with a 1 and all other objects with 0, but this results in some ambiguous infrared objects being labelled with 0 because they were slightly too far away to be "nearest". This problem would still exist with nonbinary labels, but I think it would be considerably more misleading. Options include leaving the labels binary, or somehow labelling based on distance. I'm inclined to prefer the former since the latter is considerably more difficult, but maybe there's a lot to be gained by the latter(?).

**Comment by chengsoonong** [comment]
I think forcing the labels to be binary is the way to go, as long as the procedure to do so is documented (the code is available anyway).

Once this is done, and @jbanfield can run your whole pipeline, put the dataset up on zenodo.org (add me, username cong, so that I can edit it in future). There is a 2GB size limit, so some care would need to be taken.

**Comment by MatthewJA** [comment]
Okay. In that case, the dataset's all ready. I'll write something up soon.

@jbanfield: Let me know if you need help getting the code running.

**Comment by jbanfield** [comment]
I'll be back in town on the weekend, so this is my task on Monday.  Will let you know how it goes.
