### ISSUE TITLE
run code on ELAIS

### ISSUE THREAD

**Issue by jbanfield** [chengsoonong/crowdastro#193]

**Comment by MatthewJA** [comment]
Ran the CDFS-trained classifier on ELAIS-S1 and attained an accuracy of 84%, which is very close to the 85% attained on CDFS. We must have made some mistake in the code the other week.

Here's an image of the predictions (red) against the Middelberg labels (green):
![image](https://cloud.githubusercontent.com/assets/2681312/20026548/71d444bc-a350-11e6-83ce-7815c67b017d.png)

As you can see, there's a large section where Middelberg don't have labels, which drops our accuracy a little bit. You can also see that for every ATLAS object, we pick up multiple host galaxies &mdash; that's because we are only looking at each galaxy individually. Cleverly associating each ATLAS object with _one_ host galaxy would likely dramatically improve performance.

**Comment by MatthewJA** [comment]
Pushed a notebook (above) with these results and the code to reproduce them. You will also need the Middelberg labels, which I have attached here.
[middelberg_2008_atlas_classifications.txt](https://github.com/chengsoonong/crowdastro/files/572939/middelberg_2008_atlas_classifications.txt)
