### ISSUE TITLE
Click consensus

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#24]
Work out the distribution of peaks that labellers choose. The goal is to decide whether choosing the peak with the most votes is a good choice.
- ratio between first and second
- ratio between first and sum of everything else
- convert to probability and compute entropy

**Comment by MatthewJA** [comment]
Results seem to indicate that the _vast_ majority of subjects have complete agreement, provided that volunteers agree on which radio emissions come from the same source. Majority vote should work fine.

I didn't worry about entropy since the number of disagreements is so small. I suspect there may be some bugs in my code, however, so I would like to retry this after fixing those.
