### ISSUE TITLE
Investigate mean of each class

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#26]
Mean in feature space, and mean in image space of:
- IR
- Radio
  Where two classes are host galaxies and non-host galaxies

**Comment by MatthewJA** [comment]
The mean IR image of each galaxy is the same, regardless of whether there is a radio source in that galaxy.

The mean radio image differs depending on whether there is a radio source, though this may be due to noise (low sample size for having a radio source).

Haven't done feature space, as I don't have a feature space yet, but I expect the same result.
