### ISSUE TITLE
Read "active learning from crowds"

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#5]
http://www.cs.columbia.edu/~prokofieva/CandidacyPapers/Yan_AL.pdf

**Comment by chengsoonong** [comment]
http://arxiv.org/abs/1209.3686

**Comment by chengsoonong** [comment]
I think we should be able to extend the paper below to the case when we have a real number, instead of just two classes of labellers.
https://www.ischool.utexas.edu/~ml/papers/nguyen-hcomp15.pdf

**Comment by MatthewJA** [comment]
I've read Yan et al. and Mozafari et al; skimmed Nguyen et al. Thoughts:
- Crowdsourcing brings two main problems: label noise, and multiple annotators. Yan et al. consider both and increase classification accuracy as a result. However (as far as I can tell) they don't present results separating out the two problems. This is interesting because their approach involves choosing which annotator to query for any given data point &mdash; we don't really have that luxury since a lot of RGZ annotations come from volunteers that only contribute small numbers of annotations (making predicting volunteers' fit to a specific task difficult or impossible), and we don't have a pool of labellers available to us (rather, labellers come and go and we must make do with what we have). [Sheng et al. (2008)](http://dl.acm.org/citation.cfm?id=1401965) mention that in some scenarios it's preferable to query the highest-quality labeller rather than relabel data points, so it's quite possible that the experiments in Yan et al. often choose to use the best labeller rather than spreading out the load amongst all labellers.
- Mozafari et al. estimate how many times data points should be relabelled. This roughly corresponds to the completeness cutoffs in the RGZ, where "easy" sources (compact sources, if I recall correctly) are served 5 times and "hard" sources (all else) are served 20 before being considered "complete". This is in the database as radio_subjects.classification_count and radio_subjects.complete.
- They also use two approaches: "upfront" and "iterative". I believe we care about the iterative case, so we can incorporate volunteers' labels into our query decisions.
- I'm not sure what you mean by adapting the Nguyen et al. paper to a real number scenario. Do you mean instead of treating the radio/infrared matching task as a binary classification problem?

Edit: I am incorrect. Yan et al. do separate out the labeller selection from the label noise problem, and get (considerably) worse results without labeller selection. However, they choose to use majority vote to solve the label noise problem &mdash; perhaps there's a better way?

**Comment by chengsoonong** [comment]
I think majority vote is the best thing to try first. Once that's working, we can consider more complex strategies, e.g. weighted majority vote where the weight is based on prior performance of the expert.

Regarding generalising Nguyen, Wallace and Lease, instead of considering only two types of labellers (crowd and expert), we consider an arbitrary number of labellers. Basically, we take all our crowd labellers, and give each person a score (indicating how well they perform). So now we need to work out which labeller to use. Instead of asking whether to use crowd or expert, we ask "what score labeller should I use?".

**Comment by chengsoonong** [comment]
Please start a LaTeX document, and write up what you understood by reading the three papers above (about 0.5 - 1 page). Then close this issue.

**Comment by MatthewJA** [comment]
Closing this issue for now since we're moving this further back (and the original issue is resolved). We can either open "Finish active learning summary" later or reopen this later.
