### ISSUE TITLE
pyanno

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#64]
It might be worth seeing whether this lets us say something about the quality of the annotators.
https://pypi.python.org/pypi/pyanno

**Comment by MatthewJA** [comment]
> The documentation is hosted at http://github.enthought.com/uchicago-pyanno/ .

Documentation seems to have been relocated to [here](http://docs.enthought.com/uchicago-pyanno/).

This looks really cool! As far as I can tell it seems to only work on classes, so we'd probably need to represent the volunteers' classifications in the same way we're dealing with them in the classifier. I'm not sure if that's a bad thing. Alternatively, it seems pretty extendable, so maybe it's not too hard to make it work on real-valued labels. (Or maybe I'm not reading deep enough and it already works on real-valued labels.)

It also lets you sample from an annotation distribution, so that's pretty cool too.
