### ISSUE TITLE
theano vs tensorflow

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/crowdastro#90]
[weights.zip](https://github.com/chengsoonong/crowdastro/files/315513/weights.zip)

Not really an issue, but worth a quick sanity check.

I attach two files, one trained using tensorflow, another trained using theano, both on CPU on Mac.
100 epochs, batch size 256.

**Comment by MatthewJA** [comment]
Tensorflow:
![image](https://cloud.githubusercontent.com/assets/2681312/16141071/d77c5e0a-349a-11e6-8da9-4c7f82c2dd73.png)

Theano:
![image](https://cloud.githubusercontent.com/assets/2681312/16141075/dd3d1348-349a-11e6-8f39-ff1fee0f0d19.png)

**Comment by MatthewJA** [comment]
If the pixel feature size changes, then we'd expect changes in the filters, right? If so, I think we need to retrain these, because it turns out that ATLAS is actually 2.5x smaller than it appears in the RGZ subjects (and I've just swapped to using the original ATLAS data for future compatibility - #70). Currently working on some code that will allow that without much hassle.

**Comment by chengsoonong** [comment]
Yes, we will need new filters if there is a change between arc seconds and number of pixels.
